## Worker model naming reference:
# L2 = Llama 2
# 13B = 13B model size
# U = Uncensored
# L1 = CPU tier 1, X1 = GPU tier 1
# 001 = Worker number
# T = Testing

[[workers]]
id = "L2-13BU-L1-001T"
model = "L2-13BU-L1"
uncensored = true
address = "http://192.168.2.109:2864"
tier = 1

[[workers]]
id = "L2-13BU-L1-002T"
model = "L2-13BU-L1"
uncensored = true
address = "http://192.168.2.109:2865"

[[workers]]
id = "L2-13BU-L1-003"
size = "13B"
model = "L2-13BU-L1T"
uncensored = true
address = "http://192.168.2.109:2866"