<script setup lang="ts">
import { Subscriptions, User } from "~/db/entities/User";

const user = (await useFetch(`/api/user/get`)).data.value as User;

definePageMeta({
	layout: "account",
	middleware: "auth",
});

const language = navigator.language;

const includedFeatures = [
	"Unlimited access to all models",
	"Code generation models",
	"Mathematics models",
	"Future updates",
];

if (!user)
	navigateTo(
		"/auth/login?" +
			new URLSearchParams({
				next: "/",
			})
	);

const token = useCookie("token");

const buyPremium = () => {
	useFetch(`/api/billing/order`, {
		method: "POST",
		body: JSON.stringify({
			product: "PREMIUM",
		}),
		headers: {
			"Content-Type": "application/json",
			Authorization: `Bearer ${token.value}`,
		},
	}).then(res => {
		res.data.value?.url && window.open(res.data.value.url, "_blank");
	});
};
</script>

<template>
	<div
		class="!h-[100dvh] h-screen overflow-y-scroll grow bg-dark-400 no-scrollbar">
		<header class="relative isolate pt-16 w-full">
			<div
				class="absolute inset-0 -z-10 overflow-hidden"
				aria-hidden="true">
				<div
					class="absolute left-16 top-full -mt-16 transform-gpu opacity-50 blur-3xl xl:left-1/2 xl:-ml-80">
					<div
						class="aspect-[1154/678] w-[72.125rem] bg-gradient-to-br from-orange-500 to-red-600"
						style="
							clip-path: polygon(
								100% 38.5%,
								82.6% 100%,
								60.2% 37.7%,
								52.4% 32.1%,
								47.5% 41.8%,
								45.2% 65.6%,
								27.5% 23.4%,
								0.1% 35.3%,
								17.9% 0%,
								27.7% 23.4%,
								76.2% 2.5%,
								74.2% 56%,
								100% 38.5%
							);
						" />
				</div>
				<div class="absolute inset-x-0 bottom-0 h-px bg-gray-100/5" />
			</div>

			<div class="mx-auto max-w-6xl px-4 py-10 sm:px-8 lg:px-10">
				<div
					class="mx-auto flex max-w-2xl items-center justify-between gap-x-8 lg:mx-0 lg:max-w-none">
					<div class="flex items-center gap-x-6">
						<div
							class="h-16 w-16 flex items-center justify-center rounded ring-1 ring-gray-100/10 p-2">
							<Icon
								name="fluent-emoji:dollar-banknote"
								class="w-12 h-12 mb-2" />
						</div>
						<h1>
							<div
								class="mt-1 text-xl font-semibold leading-6 text-gray-50">
								Subscriptions
							</div>
							<div class="text-sm leading-6 text-gray-400">
								Your subscriptions
							</div>
						</h1>
					</div>
				</div>
			</div>
		</header>
		<div class="max-w-6xl mx-auto p-4 xl:p-10">
			<div
				:class="[
					'p-4 w-full rounded-lg flex flex-row bg-dark-800 ring-1 ring-gray-800 items-center gap-4',
					user.credits <= 0 && 'ring-red-500 ring-2',
				]">
				<div
					class="h-16 w-16 flex items-center justify-center rounded ring-1 ring-gray-100/10 p-2">
					<Icon name="fluent-emoji:computer-disk" class="w-12 h-12" />
				</div>
				<h1 class="grow">
					<div
						class="mt-1 text-lg font-semibold leading-6 text-gray-50">
						{{ user.credits }} credits left
					</div>
					<div class="text-sm leading-6 text-gray-400">
						One credit amounts to one character generated by an AI
					</div>
				</h1>
				<div class="h-full">
					<Button
						theme="gray"
						class="h-full"
						disabled
						title="Not available yet"
						>Buy</Button
					>
				</div>
			</div>
			<div
				class="mx-auto mt-16 bg-dark-800 flex lg:flex-row flex-col items-center rounded-lg ring-1 ring-gray-800 shadow sm:mt-16 lg:flex">
				<div class="p-8 sm:p-10 lg:flex-auto">
					<h3 class="text-2xl font-bold tracking-tight text-gray-50">
						AIP Supporter
					</h3>
					<p class="mt-6 text-base leading-7 text-gray-300">
						Supercharge your AI experience with unlimited access to
						every model, including code generation models.
					</p>
					<div class="mt-10 flex items-center gap-x-4">
						<h4
							class="flex-none text-sm font-semibold leading-6 text-orange-300">
							What’s included
						</h4>
						<div class="h-px flex-auto bg-gray-800" />
					</div>
					<ul
						role="list"
						class="mt-8 grid grid-cols-1 gap-4 text-sm leading-6 text-gray-300 sm:grid-cols-2 sm:gap-6">
						<li
							v-for="feature in includedFeatures"
							:key="feature"
							class="flex gap-x-3">
							<Icon
								name="tabler:check"
								class="h-6 w-5 flex-none text-orange-300"
								aria-hidden="true" />
							{{ feature }}
						</li>
					</ul>
				</div>
				<div
					class="-mt-2 p-4 lg:mt-0 lg:max-w-md lg:flex-shrink-0 w-full">
					<div
						class="rounded-lg bg-dark-500 py-10 text-center ring-1 ring-inset ring-gray-900/5 lg:flex lg:flex-col lg:justify-center lg:py-16">
						<div class="mx-auto max-w-xs px-8">
							<p class="text-base font-semibold text-gray-300">
								Paid every month
							</p>
							<p
								class="mt-6 flex items-baseline justify-center gap-x-2">
								<span
									class="text-5xl font-bold tracking-tight text-gray-50"
									>{{
										Intl.NumberFormat(language, {
											style: "currency",
											currency: "EUR",
										}).format(10)
									}}</span
								>
								<span
									class="text-sm font-semibold leading-6 tracking-wide text-gray-300"
									>EUR</span
								>
							</p>
							<Button
								:disabled="
									user.subscription === Subscriptions.PREMIUM
								"
								theme="orange"
								class="w-full mt-6"
								@click="buyPremium">
								{{
									user.subscription === Subscriptions.PREMIUM
										? "Subscribed!"
										: "Get access"
								}}
							</Button>
							<p class="mt-6 text-xs leading-5 text-gray-300">
								Invoices and receipts available for easy company
								reimbursement
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>
